version: '3.8'
services:
    nocs-apps-php:
        container_name: nocs-apps-php
        build:
            context: ./
            dockerfile: images/php/Dockerfile
        depends_on:
            - nocs-mysql
        links:
            - nocs-mysql
        ports:
            - "8080:80"
        networks:
            - nocs-network
        volumes:
            - ./config/apache/default.conf:/etc/apache2/sites-enabled/default.conf
            - type: bind
              source: ./src
              target: /var/www/html
    nocs-mysql:
        container_name: nocs-mysql
        platform: linux/x86_64
        image: mysql
        restart: always
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        ports:
            - "3306:3306"
        networks:
            - nocs-network
        volumes:
            - ./storage/mysql:/var/lib/mysql
    nocs-phpmyadmin:
        container_name: nocs-phpmyadmin
        image: phpmyadmin
        ports:
            - "3305:80"
        restart: always
        environment:
            PMA_HOST: nocs-mysql
            PMA_PASSWORD: ""
        depends_on:
            - nocs-mysql
        networks:
            - nocs-network
volumes:
    src:
networks:
  nocs-network:
    external: true
